## Hyperparameter Search

In [1]:
from dependencies import *
from utils.custom_plotting import LinePlot

import pandas as pd

In [2]:
MODEL_ROOT = "D:/models/hyperparameter_search/kc46/"

plot = LinePlot( title = f'Hyperparameter Selection - KC-46 model',
                x_axis_title = 'Epochs',
                y1_axis_title = 'Validation - Segmentation Sparse Categorical Accuracy',
                y2_axis_title = 'Validation Loss' )

best: dict[str, list] = { 'KC-46 Model': [], 'Best Epoch': [], 'Seg Acc': [], 'Loss': [] }
models: dict[str, dict] = {}
for model_dir in os.listdir( MODEL_ROOT ):
    with open( f"{MODEL_ROOT}{model_dir}/final/{model_dir}_final_history.json", "r" ) as j:
        models[model_dir] = json.load( j )

        plot.add_y1_trace( np.array( models[model_dir]['segmentation_output_sparse_categorical_accuracy'] ), model_dir )
        plot.add_y2_trace( np.clip( np.array( models[model_dir]['val_loss'] ), 0, 1000 ), model_dir )

        best['KC-46 Model'].append( model_dir )
        best['Best Epoch'].append( np.argmin( np.array( models[model_dir]['val_loss'] ) ) + 1 )
        best['Seg Acc'].append( np.max( np.array( models[model_dir]['segmentation_output_sparse_categorical_accuracy'] ) ) )
        best['Loss'].append( np.min( np.array( models[model_dir]['val_loss'] ) ) )

best_df = pd.DataFrame( data = best )
display( best_df )
plot.show()
plot.get_fig().write_image( 'E:/AFIT/AAR/5_Thesis/doc/figures/hyperparameter_search/kc-46_full.png', width = 1200, height = 600 )
best_df.to_latex( 'E:/AFIT/AAR/5_Thesis/doc/tables/hyperparameter_search/kc-46_hp_search_results.tex', float_format = '%.3f' )

                       KC-46 Model  Best Epoch   Seg Acc      Loss
0           kc46_lidar_lr0001_5_20           9  0.975512  0.324124
1           kc46_lidar_lr0001_94_2         179  0.985594  0.033077
2            kc46_lidar_lr001_5_20          40  0.988262  0.044219
3            kc46_lidar_lr001_94_2         168  0.990803  0.027735
4             kc46_lidar_lr01_5_20         106  0.981280  0.077370
5             kc46_lidar_lr01_94_2         139  0.980587  0.040975
6   kc46_lidar_vanilla_lr0001_5_20         139  0.982342  0.053878
7   kc46_lidar_vanilla_lr0001_94_2         161  0.983381  0.047957
8    kc46_lidar_vanilla_lr001_5_20         161  0.989757  0.036627
9    kc46_lidar_vanilla_lr001_94_2         219  0.990046  0.041782
10    kc46_lidar_vanilla_lr01_5_20         170  0.979301  0.064955
11    kc46_lidar_vanilla_lr01_94_2         169  0.980301  0.067718

In [3]:
MODEL_ROOT = "D:/models/hyperparameter_search/kc46/"

plot = LinePlot( title = f'Best Hyperparameters for full PointNet on the KC-46 -> Initial learning rate = 0.001, decays 0.94 every 2 epochs || Validation Segmentation Accuracy -> 0.991',
                x_axis_title = 'Epochs',
                y1_axis_title = 'Validation - Segmentation Sparse Categorical Accuracy',
                y2_axis_title = 'Validation Loss' )

models: dict[str, dict] = {}
for model_dir in os.listdir( MODEL_ROOT ):
    with open( f"{MODEL_ROOT}{model_dir}/final/{model_dir}_final_history.json", "r" ) as j:
        models[model_dir] = json.load( j )

        if( model_dir == 'kc46_lidar_lr001_94_2' ):
            plot.add_y1_trace( np.array( models[model_dir]['segmentation_output_sparse_categorical_accuracy'] ), model_dir )
            plot.add_y2_trace( np.clip( np.array( models[model_dir]['val_loss'] ), 0, 2 ), model_dir )

plot.show()
plot.get_fig().write_image( 'E:/AFIT/AAR/5_Thesis/doc/figures/hyperparameter_search/kc-46_best_full.png', width = 1200, height = 600 )

In [4]:
MODEL_ROOT = "D:/models/hyperparameter_search/kc46/"

plot = LinePlot( title = f'Best Hyperparameters for Vanilla PointNet on the KC-46 -> Initial learning rate = 0.001, decays 0.5 every 20 epochs || Validation Segmentation Accuracy -> 0.990',
                x_axis_title = 'Epochs',
                y1_axis_title = 'Validation - Segmentation Sparse Categorical Accuracy',
                y2_axis_title = 'Validation Loss' )

models: dict[str, dict] = {}
for model_dir in os.listdir( MODEL_ROOT ):
    with open( f"{MODEL_ROOT}{model_dir}/final/{model_dir}_final_history.json", "r" ) as j:
        models[model_dir] = json.load( j )

        if( model_dir == 'kc46_lidar_vanilla_lr001_5_20' ):
            plot.add_y1_trace( np.array( models[model_dir]['segmentation_output_sparse_categorical_accuracy'] ), model_dir )
            plot.add_y2_trace( np.clip( np.array( models[model_dir]['val_loss'] ), 0, 2 ), model_dir )

plot.show()
plot.get_fig().write_image( 'E:/AFIT/AAR/5_Thesis/doc/figures/hyperparameter_search/kc-46_best_vanilla.png', width = 1200, height = 600 )

In [5]:
MODEL_ROOT = "D:/models/hyperparameter_search/f15_scaled/"

plot = LinePlot( title = f'Hyperparameter Selection - F-15J scaled model',
                x_axis_title = 'Epochs',
                y1_axis_title = 'Validation - Segmentation Sparse Categorical Accuracy',
                y2_axis_title = 'Validation Loss' )

best: dict[str, list] = { 'Model': [], 'Best Epoch': [], 'Seg Acc': [], 'Loss': [] }
models: dict[str, dict] = {}
for model_dir in os.listdir( MODEL_ROOT ):
    with open( f"{MODEL_ROOT}{model_dir}/final/{model_dir}_final_history.json", "r" ) as j:
        models[model_dir] = json.load( j )

        plot.add_y1_trace( np.array( models[model_dir]['segmentation_output_sparse_categorical_accuracy'] ), model_dir )
        plot.add_y2_trace( np.clip( np.array( models[model_dir]['val_loss'] ), 0, 1000 ), model_dir )

        best['Model'].append( model_dir )
        best['Best Epoch'].append( np.argmin( np.array( models[model_dir]['val_loss'] ) ) + 1 )
        best['Seg Acc'].append( np.max( np.array( models[model_dir]['segmentation_output_sparse_categorical_accuracy'] ) ) )
        best['Loss'].append( np.min( np.array( models[model_dir]['val_loss'] ) ) )

best_df = pd.DataFrame( data = best )
display( best_df )
plot.show()
plot.get_fig().write_image( 'E:/AFIT/AAR/5_Thesis/doc/figures/hyperparameter_search/f15_scaled_full.png', width = 1200, height = 600 )
best_df.to_latex( 'E:/AFIT/AAR/5_Thesis/doc/tables/hyperparameter_search/f-15_hp_search_results.tex', float_format = '%.3f' )

                               Model  Best Epoch   Seg Acc      Loss
0           f15_ne_lidar_lr0001_5_20          31  0.871504  0.877072
1           f15_ne_lidar_lr0001_94_2           1  0.866548  3.509643
2            f15_ne_lidar_lr001_5_20          84  0.890955  0.295306
3            f15_ne_lidar_lr001_94_2          65  0.887662  0.317745
4             f15_ne_lidar_lr01_5_20          32  0.881561  0.479721
5             f15_ne_lidar_lr01_94_2         108  0.883352  0.576333
6   f15_ne_lidar_vanilla_lr0001_94_2         154  0.888250  0.297052
7    f15_ne_lidar_vanilla_lr001_5_20         142  0.892409  0.285959
8    f15_ne_lidar_vanilla_lr001_94_2          54  0.891367  0.299394
9     f15_ne_lidar_vanilla_lr01_5_20          75  0.891053  0.302531
10    f15_ne_lidar_vanilla_lr01_94_2          74  0.891106  0.299663

In [6]:
MODEL_ROOT = "D:/models/hyperparameter_search/f15_scaled/"

plot = LinePlot( title = f'Best Hyperparameters for full PointNet for F-15J scaled model -> Initial learning rate = 0.001, decays 0.94 every 2 epochs || Validation Segmentation Accuracy -> 0.991',
                x_axis_title = 'Epochs',
                y1_axis_title = 'Validation - Segmentation Sparse Categorical Accuracy',
                y2_axis_title = 'Validation Loss' )

models: dict[str, dict] = {}
for model_dir in os.listdir( MODEL_ROOT ):
    with open( f"{MODEL_ROOT}{model_dir}/final/{model_dir}_final_history.json", "r" ) as j:
        models[model_dir] = json.load( j )

        if( model_dir == 'f15_ne_lidar_lr001_5_20' ):
            plot.add_y1_trace( np.array( models[model_dir]['segmentation_output_sparse_categorical_accuracy'] ), model_dir )
            plot.add_y2_trace( np.clip( np.array( models[model_dir]['val_loss'] ), 0, 2 ), model_dir )

plot.show()
plot.get_fig().write_image( 'E:/AFIT/AAR/5_Thesis/doc/figures/hyperparameter_search/f15_scaled_best_full.png', width = 1200, height = 600 )

In [7]:
MODEL_ROOT = "D:/models/hyperparameter_search/f15_scaled/"

plot = LinePlot( title = f'Best Hyperparameters for Vanilla PointNet for F-15J scaled model -> Initial learning rate = 0.001, decays 0.5 every 20 epochs || Validation Segmentation Accuracy -> 0.990',
                x_axis_title = 'Epochs',
                y1_axis_title = 'Validation - Segmentation Sparse Categorical Accuracy',
                y2_axis_title = 'Validation Loss' )

models: dict[str, dict] = {}
for model_dir in os.listdir( MODEL_ROOT ):
    with open( f"{MODEL_ROOT}{model_dir}/final/{model_dir}_final_history.json", "r" ) as j:
        models[model_dir] = json.load( j )

        if( model_dir == 'f15_ne_lidar_vanilla_lr001_5_20' ):
            plot.add_y1_trace( np.array( models[model_dir]['segmentation_output_sparse_categorical_accuracy'] ), model_dir )
            plot.add_y2_trace( np.clip( np.array( models[model_dir]['val_loss'] ), 0, 2 ), model_dir )

plot.show()
plot.get_fig().write_image( 'E:/AFIT/AAR/5_Thesis/doc/figures/hyperparameter_search/f15_scaled_best_vanilla.png', width = 1200, height = 600 )